export const plants = [
  {
    name: "Oregano",
    botanicalName: "planta ess",
    lightRequirements: "Sonnig",
    usageType: "Nutzpflanze",
    growthHeight: 70,
    hardy: false,
    bloomStart: "Mai",
    bloomEnd: "Juni",
    nectar: 2,
    pollen: 3,
  },
  {
    name: "große Pflanze",
    botanicalName: "planta gr",
    lightRequirements: "Halbschatten",
    usageType: "Zierpflanze",
    growthHeight: 120,
    hardy: true,
    bloomStart: "Juni",
    bloomEnd: "August",
    nectar: 1,
    pollen: 4,
  },
  {
    name: "Schattenpflanze",
    botanicalName: "planta sch",
    lightRequirements: "Schatten",
    usageType: "Zierpflanze",
    growthHeight: 30,
    hardy: false,
    bloomStart: "Juli",
    bloomEnd: "Juli",
    nectar: 2,
    pollen: 2,
  },
  {
    name: "Ballonblume",
    botanicalName: "Platycodon grandiflorus",
    lightRequirements: "Halbschatten",
    usageType: "Zierpflanze",
    growthHeight: 120,
    hardy: true,
    bloomStart: "September",
    bloomEnd: "Oktober",
    nectar: 3,
    pollen: 1,
  },
  {
    name: "Weide",
    botanicalName: "planta wei",
    lightRequirements: "Sonnig",
    usageType: "Zierpflanze",
    growthHeight: 150,
    hardy: true,
    bloomStart: "Februar",
    bloomEnd: "April",
    nectar: 4,
    pollen: 4,
  },
  {
    name: "Pflanze1",
    botanicalName: "planta1",
    lightRequirements: "Sonnig",
    usageType: "Zierpflanze",
    growthHeight: 150,
    hardy: true,
    bloomStart: "Februar",
    bloomEnd: "April",
    nectar: 4,
    pollen: 4,
  },
  {
    name: "Pflanze2",
    botanicalName: "planta2",
    lightRequirements: "Sonnig",
    usageType: "Zierpflanze",
    growthHeight: 10,
    hardy: true,
    bloomStart: "Februar",
    bloomEnd: "März",
    nectar: 1,
    pollen: 1,
  },
  {
    name: "Pflanze3",
    botanicalName: "planta3",
    lightRequirements: "Sonnig",
    usageType: "Zierpflanze",
    growthHeight: 150,
    hardy: false,
    bloomStart: "Februar",
    bloomEnd: "April",
    nectar: 4,
    pollen: 4,
  },
  ,
  {
    name: "Pflanze4",
    botanicalName: "planta4",
    lightRequirements: "Sonnig",
    usageType: "Nutzpflanze",
    growthHeight: 50,
    hardy: true,
    bloomStart: "Februar",
    bloomEnd: "April",
    nectar: 4,
    pollen: 4,
  },
];
